name: build
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          cache-suffix: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          uv sync --locked --extra dev
      - name: Run tests
        run: |
          uv run --frozen -m unittest discover -v
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.14'
          cache-suffix: '3.14'
      - name: Check lockfile
        run: |
          uv lock --check
      - name: Install dependencies
        run: |
          uv sync --locked --extra dev
      - name: Run lint
        run: |
          uv run --frozen ruff check
          uv run --frozen ruff format --check
